"""autogenerate tables

Revision ID: 2e2d85d6529
Revises: 
Create Date: 2015-07-21 21:05:48.761163

"""

# revision identifiers, used by Alembic.
revision = '2e2d85d6529'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("messages", "coinbase_messages")
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
