"""Removing JSONB document

Revision ID: fae9c7cbb6
Revises: b8fc854dde
Create Date: 2015-08-10 06:16:43.167606

"""

# revision identifiers, used by Alembic.
revision = 'fae9c7cbb6'
down_revision = 'b8fc854dde'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_json_doc_key', 'coinbase_messages', type_='unique')
    op.drop_column('coinbase_messages', 'json_doc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coinbase_messages', sa.Column('json_doc', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.create_unique_constraint('messages_json_doc_key', 'coinbase_messages', ['json_doc'])
    ### end Alembic commands ###
